version: '3.8'

services:
  app:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
